### ISSUE TITLE
No stdout for node v18

### ISSUE THREAD

**Issue by mikeboiko** [codetheweb/anylist#25]
Hi, I tried to run the following code but nothing happened nor did I get any stdout/stderr:

```
const AnyList = require('anylist');

const any = new AnyList({email: '<email>', password: '<pw>'});

any.on('lists-update', lists => {
  console.log('Lists were updated!');
});

any.login().then(async () => {
  await any.getLists();

  // Add new item to the Walmart list
  const walmart = any.getListByName('Task');
  let chips = any.createItem({name: 'Chips'});
  chips = await walmart.addItem(chips)
  await chips.save();

  any.teardown();
});
```

I installed the `anylist` package and ran this in my terminal on Linux:
```
╭─mike@asus ~/temp/anylist  ‹master*›
╰─➤  node --version
v18.9.1
╭─mike@asus ~/temp/anylist  ‹master*›
╰─➤  node script.js
```

Could you please let me know if I need to do anything differently?

**Comment by codetheweb** [comment]
Try adding some logging to see what's getting returned / if login is working.

**Comment by mikeboiko** [comment]
Hi, for some reason my reply a week ago didn't save, so let me post it again.
I added the following logging:
```
any.login().then(async () => {
  await any.getLists();

  // Add new item to the Walmart list
  const walmart = any.getListByName('Task');
  console.log(walmart);
  let chips = any.createItem({name: 'Chips'});
  console.log(chips);
  chips = await walmart.addItem(chips)
  console.log(chips);
  await chips.save();

  any.teardown();
});
```

I'm still not seeing any stdout when I run `node script.js`
I'm not super familiar with node though. Should I be logging in a different way/place?

Thanks!

**Comment by codetheweb** [comment]
You should be seeing something with that--not sure what else could be the issue, sorry.

**Comment by mikeboiko** [comment]
Ok thanks for confirming.
Which version of node are you using?

**Comment by mikeboiko** [comment]
I just downgrade to node v12.22.12 and everything works great!
Feel free to close this issue and make it work for the latest node later.
