### ISSUE TITLE
Can we get the price / Total cost from Nodejs?

### ISSUE THREAD

**Issue by Mannitou** [codetheweb/anylist#26]
Hello,

I know that we get the quantity but can I get the total cost of an item?

picture of Anylist:
[https://help.anylist.com/img/articles/item-prices/adjust-quantity-for-total-cost-1.png](url)

I am trying to keep track of my budget with the anylist software.

Thanks,

Pascal Manni

**Comment by codetheweb** [comment]
I don't remember all the data that's returned but I believe this should be available.

Did you try it out yet?

**Comment by Mannitou** [comment]
thanks for your message,

I find in "anylist/lib/definitions.json":
{"rule":"optional","type":"PBItemPrice","name":"itemPrice","id":16}

but if I go to anylist/lib/item.js
I cannot find any constructor or methode to get the itemPrice and totalPrice ( Quantity * itemPrice).

I belive we need some extra line to make it available.

**Comment by codetheweb** [comment]
I see, happy to accept a PR for it. :)
