### ISSUE TITLE
Get recent items for a list

### ISSUE THREAD

**Issue by kevdliu** [codetheweb/anylist#28]
Hello, 

Thank you so much for making this library! With Google removing third-party shopping list support in Google Assistant, I was able to use this library to integrate Anylist with Home Assistant. The only thing missing is automatic categorization of items. I'm not too familiar with the Anylist API but it seems like they are doing that client side? One idea I have for automatically categorizing items is use the recent items list as a lookup table for the category of an item. This way, once I manually assign a category to an item, future insertions of the item will have the same category applied.

**Comment by kevdliu** [comment]
Never used protobuf before but I'm slowing getting more familiar with it. Going to see if I can create a PR for it

**Comment by kevdliu** [comment]
Opened a PR here https://github.com/codetheweb/anylist/pull/29

**Comment by Daneish** [comment]
Hi kevdliu, if you were willing to share your AnyList Home Assistant integration, I would love to use it!

**Comment by kevdliu** [comment]
> Hi kevdliu, if you were willing to share your AnyList Home Assistant integration, I would love to use it!

Yeah sure I can try to clean it up and put it up on my github.

**Comment by shirasp** [comment]
Same here! I would love to have my AnyList available in Home Assistant!

**Comment by Daneish** [comment]
> Yeah sure I can try to clean it up and put it up on my github.

That would be excellent, thank you so much!

**Comment by kevdliu** [comment]
Hopefully I'll have some time in the coming weekend(s) to get around to it, I'll update here when it's up. With home assistant 2023.8 adding support for intent wildcards I'm planning to migrate to that instead of my current implementation.

**Comment by kevdliu** [comment]
Found some time this weekend to put it on Github. For everything to work you need both an addon (which runs a server that uses this library to communicate with Anylist) and a custom integration (which interfaces Home Assistant with the addon). 

The addon is here: https://github.com/kevdliu/hassio-addon-anylist
The custom integration is here: https://github.com/kevdliu/hacs-anylist. 

If you run into an issues or have questions please post them in the issue tracker of the corresponding repository.

**Comment by codetheweb** [comment]
very cool, happy to link to those from the readme in this repo if you open a PR :)

**Comment by Daneish** [comment]
> Found some time this weekend to put it on Github. 

That’s amazing! Thank you so much for this. I’ve got it working, and I’m playing around with it now.

> If you run into any issues or have questions please post them in the issue tracker of the corresponding repository.

Will do!
