### ISSUE TITLE
Nothing happens...

### ISSUE THREAD

**Issue by jchadwick** [codetheweb/anylist#33]
Running the example from the homepage nothing happens. The app just exits - no error or message or anything.
How come nothing is displayed?

Steps to reproduce:

1. Init/install
  ```sh
  npm init -y
  npm i anylist
  ```

2. Copy example from homepage into `index.js`
3. Change email/password
4. `node index.js`

...nothing.

Node version v19.0.0

**Comment by jchadwick** [comment]
I nvm'ed down to 12.7.0 and the same code works as-is.  Looks like this is a problem with more recent versions of Node.

**Comment by kevdliu** [comment]
I updated my node installation to the latest v20.8.1 and it's working for me. Could you add some print statements inside the callback for `any.login().then()` to see where it's unexpectedly exiting?

**Comment by jchadwick** [comment]
Yeah, I recently installed this on v21.2.0 and everything was fine.  Happy to close this now, I guess, but note that some versions of Node (19.x?) might still be broken.
